### PR TITLE
Add a net.minetest.app.git file which builds the latest git version of minetest, as well as corresponding instructions in the README.

### PR DESCRIPTION
**Pull request by casept**

### CODE REVIEW

**Comment by est31** [comment]
Thanks!

**Comment by est31** [comment]
@casept I don't really want to maintain the project any more. If I give you contributor access can you adopt the repo?

**Comment by est31** [comment]
(and maintain it)

**Comment by casept** [comment]
Sure, I have enough free time on my hands.

**Comment by est31** [comment]
@casept sent you an invite

**Pull request merged**
